
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint with Pylint
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt

      - name: Lint with Pylint
        run: |
          pylint --recursive=y --fail-under=7.50 .

  test:
    runs-on: ubuntu-latest
    name: Test with pytest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-asyncio
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          pytest
